### ISSUE TITLE
some stuff needed for 0.51.0

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1020]
Just a small reminder list I can add to the [0.51.0](https://github.com/Unvanquished/Unvanquished/milestone/22) milestone.

- [x] Get the battlesuit out _(it's in game)_;
- [x] Ensure battlesuit soundsteps are played while using new model (see #1060);
- [x] Merge invis's damage indicators;
- [x] See where the goon is at _(it's now in game)_;
- [x] Ensure the new goon model is correctly rendered when `animation.cfg` is deleted as expected;
- [x] New goon needs to be made bigger;
- [x] Adjust model z-offsets since they was relying on a broken mechanism which is now fixed: check human naked model which have their feet on the floor, and some other aliens too, also check buildable gibs to lay on the floor (both teams);
- [x] Remove drill model and use repeater one instead, see [res-buildables#2](https://github.com/UnvanquishedAssets/res-buildables_src.dpkdir/issues/2) and #1062.
- [x] Daemon's [unv/for-0.51.0 milestone](https://github.com/DaemonEngine/Daemon/milestone/1).
- [x] Assets repositories.
- [x] [Map build reproduceability](https://github.com/UnvanquishedAssets/UnvanquishedAssets/issues/2).

**Comment by illwieckz** [comment]
damage indicators were tested in game this latest sunday and it was well received!

**Comment by DolceTriade** [comment]
Goon needs to be made bigger.

**Comment by illwieckz** [comment]
I have to triple-check it but it looks like goon eyes are not rendered correctly (it's so subtle that if we release it as is a very few will notice or perhaps no one except those who worked on it).

**Comment by illwieckz** [comment]
iirc, with new gameplay changes, the repeater is not needed anymore, drill both mines bp and provides bp for its area. So we have to remove a bubble in build menu screen. Also, it means we can use the repeater model as drill model (since it looks better and is animated, and basically looks like a small reactor). @Viech can you confirm?

**Comment by illwieckz** [comment]
making a `for-0.51.0` branch with damage indicators, newgoon, and newbsuit will make this issue fixed.

**Comment by illwieckz** [comment]
well, we probably have to add some commits to remove the drill and use the repeater model instead.

**Comment by illwieckz** [comment]
battlesuit step sound still broken

**Comment by illwieckz** [comment]
That bug is known since the beginning, but newgoon still needs the obsolete unneeded `animation.cfg` file being there to be rendered and animated properly:

![broken](http://dl.illwieckz.net/b/unvanquished/bugs/newgoon-animation/20171101-142422-000.unvanquished-newgoon-animation.jpg)

Note that there is also a warning for the bsuit but this one is rendered correctly:

![warn](http://dl.illwieckz.net/b/unvanquished/bugs/newgoon-animation/20171031-221101-001.unvanquished-newgoon-animation.png)

Note that to trigger the goon bug, using an extrapaks is not enough, `models/level3/animation.cfg` must be absent from _all_ packages.

**Comment by Viech** [comment]
> iirc, with new gameplay changes, the repeater is not needed anymore […]. So we have to remove a bubble in build menu screen. Also, it means we can use the repeater model as drill model (since it looks better and is animated, and basically looks like a small reactor). @Viech can you confirm?

Yes, this is the intended change if we keep build-everywhere. Just to be precise:

> drill both mines bp and provides bp for its area

is not correct as you can build without area restrictions.

**Comment by illwieckz** [comment]
Some optional fixes that could be great to have but can be postponed:

- [ ] #1058 dead player models float a bit above the ground
- [ ] #1059 buildables remains do not lay on floor after explosion

**Comment by zorun** [comment]
It's been exactly 2 years today since the release of 0.50

Any plans for the 0.51 release soon? :)

**Comment by illwieckz** [comment]
Everything that is required to be fixed before release is fixed now.
