### ISSUE TITLE
Lack of feedback when playing aliens

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1297]
Playing aliens is hard, and takes quite some skill. I think one thing that's missing is feedback.

I can see various issues, already but maybe there are more:

* [ ] You have no feedback on the marauder electrical attack range https://github.com/Unvanquished/Unvanquished/issues/1291
* [ ] You have no feedback on the marauder electrical attack charge https://github.com/Unvanquished/Unvanquished/issues/1292
* [ ] You have no feedback on the melee attack range, so you never know if the enemy is too far or not https://github.com/Unvanquished/Unvanquished/issues/1293
* [ ] You have no feedback (by default) on when you can hit/shot/bite again https://github.com/Unvanquished/Unvanquished/issues/1294
* [ ] You have no feedback on how much your barb shot will get deviated, or the fact that it will be fired straight at all https://github.com/Unvanquished/Unvanquished/issues/1295
* [ ] You have no feedback on where the ground is when wallwalking https://github.com/Unvanquished/Unvanquished/issues/1296

This is a bit of a meta issue, individual issues should be discussed in their own issue. Add or suggest more if you have more in mind.
