### ISSUE TITLE
Make skilled bots "dance"

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2203]
Human players try to dance with their opponent, to dodge damage without necessarily fleeing. Bots should do that.

This probably requires to fix at least those issues as pre-requisite

- [ ] #1673 so that they don't end up falling in holes or stuck in walls
- [ ] #2084  so that they don't shoot at friends
- [ ] #2077 so that they dance more or less nicely
- [X] #2137 to know how to stay behind or on sides
