### ISSUE TITLE
0.54.1 release thread (stuff to do before the release)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2387]
This issue is to track ideas to improve the release process, in foresight of next release. Please edit it at will.

Outstanding PR and issues ("must have"):
- ~~none~~

Milestones ("would have"):
- [x] https://github.com/Unvanquished/validate-release/pull/4
- [x] https://github.com/Unvanquished/release-scripts/pull/30

Tasklist
- ~~Emit notices to server owners about the upcoming release to give them time to prepare instances~~

## Release process:

- Prepare blog post
  * ~~Gather the changes (list commits)~~
  * ~~Summarize the changes (for the redactor)~~
  * [x] Write a blog post
  * [x] Proof read blog post
- ~~Write release notes for server owners to ease the transition (includes things like how to update the build repos)~~
- Merge
  * ~~Merge remaining PRs (see above)~~
  * ~~Merge `0.54.1/sync` to master if exists~~
- [x] Commit version numbers and push commits
- Tag release
  * [x] tag release
  * [x] tag every submodule of Unvanquished and UnvanquishedAssets with `unvanquished/0.54.1`
  * [ ] tag Urcheon
  * [x] Push release tags
- Build release
  * Rebuild engine binaries
    - [x] Linux (linux-amd64, linux-i686, linux-arm64, linux-armhf)
    - [x] Windows (windows-amd64, windows-i686)
    - [x] macOS (macos-amd64)
  * Rebuild dpks
    - [x]  Rebuild game nexes
    - [x] Rebuild data
    - [x] Package dpks
    - [x] Package unizip
  * [x] Build and upload benchmark demo
  * [x] Check with validate-release
- Set up game servers
  * [x] unvanquished.net
  * [x] gg.illwieckz.net
- Set up distribution
  * [x] Upload unizip to dl.unvanquished.net
  * [x] Convert unizip to torrent in cdn.unvanquished.net
  * [ ] Make sure CDN mirrors mirrored
  * [x] Upload to GitHub
  * [x] Run script to set 0.54.1 default download
  * [x] Run script to publish torrent
- [x] Publish blog post
- Social medias
  * [x] Write and publish Mastodon post
  * [x] Write and publish X post
  * [x] Write and publish Facebook post
  * [x] Write and publish Reddit post
- [x] `@everyone` message on chat (also write announcement post in discord)
- [x] Update flatpak recipe

## Post-release things:

- [ ] Make sure FOSS Torrents knows about the release
- [x] Make sure Phoronix knows about the release
- ~~Translate blog post for LinuxFr.org or make sure someone writes an article about the release~~
- [x] Upload to sf.net as a backup
- [x] Upload to IndieDB as a backup
- ~~Copy blog post to IndieDB~~
- [x] Duplicate this issue for 0.55.0

**Comment by slipher** [comment]
Based on the current state of things it seems like there is probably no reason to rebuild the engine

**Comment by bmorel** [comment]
based on current number of changes, a 0.54.1 would probably be a bit of a lie as we're far from having only bug fixes or minor improvements. There are new commands and bots moves fare better while maybe they'll stop being incredibly stupid or OP as in 0.54.0.

**Comment by illwieckz** [comment]
My work log:

```bash
export TZ='GMT'
export GIT_AUTHOR_DATE='2023-12-10 16:00:00+00:00'
export GIT_COMMITTER_DATE="${GIT_AUTHOR_DATE}"

cd ~/Mapping/Unvanquished/UnvanquishedAssets

# We assume all submodules are already committed.
# TODO: Document how to do that.

git-checkout-modules --pull --current-branch

git -C pkg/res-weapons_src.dpkdir tag -am 'res-weapons 0.54.1' v0.54.1
git -C pkg/res-buildables_src.dpkdir tag -am 'res-buildables 0.54.1' v0.54.1

get some older commits, we won't rebuild those packages

git -C pkg/map-chasm_src.dpkdir checkout unvanquished/0.54.0
git -C pkg/map-forlorn_src.dpkdir checkout unvanquished/0.54.0
git -C pkg/tex-common_src.dpkdir checkout unvanquished/0.54.0

git add pkg/map-chasm_src.dpkdir pkg/map-forlorn_src.dpkdir pkg/tex-common_src.dpkdir

git commit

# Unvanquished 0.54.1
#
# We don't build those packages in 0.54.1 release,
# so we commit old references.

git push

git submodule foreach git tag -am 'Unvanquished 0.54.1 beta' unvanquished/0.54.1
git tag -am 'Unvanquished 0.54.1 beta' unvanquished/0.54.1
git tag -am 'Unvanquished 0.54.1 beta' v0.54.0

urcheon build -r unvanquished/0.54.0 pkg/res-buildables_src.dpkdir pkg/res-weapons_src.dpkdir
urcheon package pkg/res-buildables_src.dpkdir pkg/res-weapons_src.dpkdir

7z x build/pkg/res-weapons_0.54.1.dpk DEPS
sed -e 's/0.54/0.54-dirty/' -i DEPS
7z -tzip a build/pkg/res-weapons_0.54.1.dpk DEPS
rm DEPS

cd ~/dev/Unvanquished

# We assume all submodules are already committed.
# TODO: Document how to do that.

git-checkout-modules --pull --current-branch

./update-version-number.py 0.54.1
git -C daemon commit -am 'Update version number to 0.54.1'
git -C daemon push
git add daemon
git commit -am 'Update version number to 0.54.1'
git push

git -C daemon tag -am 'Daemon 0.54.1 beta' v0.54.1
git tag -am 'Unvanquished 0.54.1 beta' v0.54.1

git -C daemon submodule foreach git tag -am 'Unvanquished 0.54.1 beta' unvanquished/0.54.1
git submodule foreach git tag -am 'Unvanquished 0.54.1 beta' unvanquished/0.54.1
git tag -am 'Unvanquished 0.54.1 beta' unvanquished/0.54.1

urcheon build pkg/unvanquished_src.dpkdir
urcheon package pkg/unvanquished_src.dpkdir

export UNVANQUISHED_COMMIT="$(git rev-parse HEAD)"

cd ~/dev/unvanquished-release-scripts

rm -r build/release

time ./docker-build --reference "${UNVANQUISHED_COMMIT}" --targets all

./docker-build --unizip

cd build/release

7z x unvanquished_0.zip

cd unvanquished_0/pkg

cp ~/dev/Unvanquished/build/pkg/unvanquished_0.54.1.dpk .
cp ~/Mapping/Unvanquished/UnvanquishedAssets/build/pkg/res-buildables_0.54.1.dpk .
cp ~/Mapping/Unvanquished/UnvanquishedAssets/build/pkg/res-weapons_0.54.1.dpk .

mkdir vm
cd vm
7z x ../vm_0.dpk
7z -tzip a ../unvanquished_0.54.1.dpk
cd ..
rm -r vm vm_0.dpk

cd ..
find . -exec touch --date="${GIT_AUTHOR_DATE}" {} \;

find pkg -type f -name '*.dpk' -print0 | drt-multitask -0 -I{} -P$(nproc) drt-zipbrute --no-directories --touch --chmod -4 {}
find . -type f -name '*.zip' -print0 | drt-multitask -0 -I{} -P$(nproc) drt-zipbrute --no-directories --touch --chmod -4 {}

mv symbols_0.zip symbols_0.54.1.zip

wget https://dl.unvanquished.net/release/unvanquished_0.54.0.zip
7z x unvanquished_0.54.0.zip
cp -a unvanquished_0.54.0/pkg/[rmt]*dpk pkg/
rm -r unvanquished_0.54.0 unvanquished_0.54.0.zip

cd pkg

( export LC_ALL; md5sum --binary -- *.dpk | sed -e 's/\.dpk$//' | sort -k2,2 -t' ' | sed 's/$/.dpk/' ) | tee md5sums

touch --date="${GIT_AUTHOR_DATE}" md5sums

cd ../..

mv unvanquished_0 unvanquished_0.54.1

7z -tzip -mx=0 a unvanquished_0.54.1.zip unvanquished_0.54.1

touch --date="${GIT_AUTHOR_DATE}" unvanquished_0.54.1.zip

drt-zipbrute --no-directories --chmod -4 unvanquished_0.54.1.zip

git -C ~/dev/unvanquished-validate-release pull

~/dev/unvanquished-validate-release/validate_release.py unvanquished_0.54.1.zip
# Checking the universal zip (version = '0.54.1')
# Dirty version string detected: res-weapons_0.54-dirty.dpk
# Pak dependency cycle: res-weapons_0.54.1.dpk -> res-weapons_0.54-dirty.dpk -> res-buildables_0.54.1.dpk -> res-buildables_0.54.dpk -> res-weapons_0.54.1.dpk
# Pak dependency cycle: res-weapons_0.54.1.dpk -> res-weapons_0.54-dirty.dpk -> res-buildables_0.54.1.dpk -> res-weapons_0.54.1.dpk

cd ..
mkdir -p test
cd test

7z x ../release/unvanquished_0.54.1.zip
cd unvanquished_0.54.1
7z x linux-amd64.zip

./daemon
	/quit

cd ../../release

sha512sum -b unvanquished_0.54.1.zip | tee unvanquished_0.54.1.sha512sum
touch -r unvanquished_0.54.1.zip unvanquished_0.54.1.sha512sum

rsync -av unvanquished_0.54.1.zip unvanquished.net:
rsync -av unvanquished_0.54.1.sha512sum unvanquished.net:

firefox https://github.com/Unvanquished/Unvanquished/releases/new
# zip and sha512sum

cd ~/dev/Unvanquished
git -C daemon git submodule foreach git push --tags
git submodule foreach git push --tags
git push --tags

cd ~/Mapping/Unvanquished/UnvanquishedAssets

ssh unvanquished.net

	sudo -s
		cd /var/www/dl.unvanquished.net/release
		mv ~illwieckz/unvanquished_0.54.1.zip .
		mv ~illwieckz/unvanquished_0.54.1.sha512sum .
		chown -R www-data:www-data .

		cd /var/www/tools/release
		vim configuration/current.conf
		grep game_version configuration/current.conf
		game_version='0.54.1'

		./cache-tracker-list
		./unpack
		./publish
		./announce
		/etc/init.d/nginx configtest && systemctl reload nginx

		su - unvserver

			# Stop the release candidate server.
			./daemon-server stop rc

			cd version

			unzip /var/www/dl.unvanquished.net/release/unvanquished_0.54.1.zip

			rm default

			ln -s unvanquished_0.54.1 default

			cd ..

			vim config/default/name
			# ^7[US] ^Dunvanquished.net ^20.54.1 ^9#1^*

			# Test the game server.
			./daemon-server run default
				/quit

			exit

			sytemctl enable unvserver
			sytemctl start unvserver
		exit
	exit

# Publish GitHub release draft
# Publish Wordpress release draft

# Test the updater
~/.local/share/unvanquished/base/updater

wget --content-disposition https://unvanquished.net/download/zip

cd ~/dev/Unvanquished/dist/scripts/record-benchmark-demo/

./record-benchmark-demo
mv benchmark.dm_86 unvanquished-benchmark_0.54.1.dm_86
touch --date="${GIT_AUTHOR_DATE}" unvanquished-benchmark_0.54.1.dm_86
xz -9 unvanquished-benchmark_0.54.1.dm_86
rsync -av unvanquished-benchmark_0.54.1.dm_86.xz unvanquished.net:


ssh unvanquished.net

	sudo -s
		cd /var/www/dl.unvanquished.net/benchmark
		mv ~illwieckz/unvanquished-benchmark_0.54.1.dm_86.xz .
		chown -R www-data:www-data .

		exit
	exit

cd ~/dev/unvanquished-release-scripts/build/release

rsync -av unvanquished_0.54.1.zip frs.sourceforge.net:/home/pfs/project/unvanquished/Universal_Zip

firefox https://sourceforge.net/projects/unvanquished/files/Universal_Zip/
# Set default download for: Others (let updater as default download for supported systems)

firefox https://www.indiedb.com/games/unvanquished/downloads/add/#downloadsform
# Schedule release: Release file immediately
# Category: Full Version
# Tags: Archive,Zip,Beta,Full,Release,Version
# Name: Unvanquished Beta 0.54.1 Universal
# Summary: Everything you need in one package, for Windows, Linux, and macOS. Check our website for the release post and/or Linux distro-specific packages.
# Description:
# Once extracted, also extract the system specific archive (like linux-amd64.zip) in a way the contained file (for example “daemon”) is next to the “pkg” directory.
# 
# unvanquished_0.53.2
# |- README.txt
# |- pkg/
# |- daemon
# 
# Look at the README!!!
# 
# It is recommended to use the launcher (especially on macOS!): https://unvanquished.net/download/

cd ~/dev/net.unvanquished.Unvanquished
git checkout master
git pull
git checkout -b illwieckz/release/0.54.1
vim net.unvanquished.Unvanquished.yml
vim net.unvanquished.Unvanquished.metainfo.xml 
git commit -am 'Unvanquished 0.54.1 release'
git push --set-upstream origin illwieckz/release/0.54.1

firefox https://github.com/flathub/net.unvanquished.Unvanquished/pull/new/illwieckz/release/0.54.1
```
