### ISSUE TITLE
2024-01: Project direction; Urgent, Important and Fancy things to do 

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2903]
We encourage to work in such direction.

This is the current status in January of 2024 and until this thread is closed and replaced by a new one.

Previous thread, with possible comments about reappointed goals.

- https://github.com/Unvanquished/Unvanquished/issues/2706

----

Explanation about this document:

It happens that sometime things among the more important ones are also the ones with the least personal interest. So I encourage people to look at those issues even if that's not the topic they are naturally inclined to, otherwise some of them will never be fixed.

Things can be classified as urgent and non-urgent, important and non-important. Urgent is not something higher than Important. Those are different classifications. There can be non-urgent important things, and non-important urgent things.

Things are organized this way:

&nbsp;|Urgent|not Urgent
-|-|-
Important||
not Important||
Fancy|N/A|

For simplicity not Important and not Urgent things are not listed there.

This **Important** / **Urgen**t classification is inherited from ITIL, quote from Wikipedia:

> The Information Technology Infrastructure Library (ITIL) is a set of practices and a framework for IT activities such as [IT service management](https://en.wikipedia.org/wiki/IT_service_management) (ITSM) and [IT asset management](https://en.wikipedia.org/wiki/IT_asset_management) (ITAM) that focus on aligning IT services with the needs of the business.

Though we are not a business and we don't have customers and duties.

We're a volunteer hobby project so I added a “**Fancy**” category. This project is for fun. That “_Fancy_” category is indeed totally absent of ITIL, but doing cool stuff is a good way to be motivated to work on various parts of the game and then to acquire knowledge, skill and confidence to work on other important or urgent topics. Also, it may happen that sometime fixes for Urgent or Important things may be found when working on something else (serendipity).

Urgent and Important classification is inherited from methods of working where people are all on duty, but in a fully volunteer project there is no such thing like a duty. While the important/urgent classification is a very effective discernment tool, we also need to build-up motivation and enjoyment. There cannot be any urgent meaning in the Fancy category.

---

## Important and Urgent

This is not a release blocker because all our previous releases were affected anyway, but seriously this can make rendering a map going from 300 fps to 20 fps. If it was a regression it would be a blocking one.

- [x] **engine:** https://github.com/DaemonEngine/Daemon/pull/1023

- [x] **engine:** https://github.com/DaemonEngine/Daemon/issues/1011
This one makes some maps unusable.

- [x] **engine:** https://github.com/DaemonEngine/Daemon/pull/1030

- [x] **engine:** https://github.com/DaemonEngine/Daemon/issues/849

## Important but not Urgent

Those are things we may want to make efforts at working on them, even if we are not naturally inclined to, but they are not urgent, for example we cannot block any release because of it.

- [x] **engine:** https://github.com/DaemonEngine/Daemon/issues/1010
All other portal issues that are not https://github.com/DaemonEngine/Daemon/issues/1011.

- [x] **engine:** https://github.com/DaemonEngine/Daemon/pull/992
and https://github.com/DaemonEngine/Daemon/pull/1026

- [x] **game:** https://github.com/Unvanquished/Unvanquished/issues/2700

- [ ] **game:** https://github.com/Unvanquished/gameplay/issues/61

- [ ] **data:** replace the Tremulous sound files
This is among project's goals since 11 years, we are 11 years late.

## Urgent but not Important

- [x] **game:** https://github.com/Unvanquished/Unvanquished/issues/2682 (Clang regression)

Our releases don't use an affected clang, it only affects debugging with recent clang but GCC exists.

This may become important in the future with Saigo or Wasi.

## Fancy

- [ ] **engine:** fix the PBR texture mapping
Not fixing this prevents us to recruit texture artists, and makes us unable to use actual texture libraries like https://ambientcg.com/ , https://cc0-textures.com/ , https://publicdomaintextures.com/  and others.

- [ ] **engine:** fix or reimplement the dynamic shadows
This is a regression, even Quake 3 had them 20 years ago.

- [ ] **engine:** correct lighting https://github.com/DaemonEngine/Daemon/issues/270
The renderer cannot be considered modern without that. Without that, games are condemned to look like games from the 90's.

- [ ] **game:** impact on movable surface
A game not doing that looks very primitive, some other games implemented that 20 years ago!

- [ ] **engine:** fix water code https://github.com/DaemonEngine/Daemon/issues/645 https://github.com/DaemonEngine/Daemon/issues/850
This is a regression, XreaL had it. Other engines like DarkPlaces have it. Without that, games are condemned to look like games from the 90's.

**Comment by VReaperV** [comment]
Shouldn't https://github.com/DaemonEngine/Daemon/issues/849 be either only urgent or only non-urgent? Unless it can exist in a superposition :)

**Comment by illwieckz** [comment]
> Shouldn't [DaemonEngine/Daemon#849](https://github.com/DaemonEngine/Daemon/issues/849) be either only urgent or only non-urgent? Unless it can exist in a superposition :)

Right! I deduplicated this entry. 🙂️

**Comment by illwieckz** [comment]
I also added the portal issues to the list. 🙂️

Right now the first post is still basically a copy paste of what remained not done yet from previous status, but the list may change and especially increase when I remind what to add to the list.

**Comment by slipher** [comment]
To my mind the Urgent vs. Important framework is not useful for a project like ours because issues rarely have deadlines. Bugs or the lack of features just keep existing indefinitely. In personal life you could have a task that is urgent but not important "Get a Halloween costume", because Halloween is 2 days away (urgent) but nothing bad will happen if you don't wear a costume that day (not important). The point is you can fail to complete the task by missing the deadline but it will be closed anyway.

I don't understand what illwieckz is going for with this distinction.
