### ISSUE TITLE
0.55.1 release thread (stuff to do to produce, publish, and announce the release)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#3166]
This issue is to track ideas to improve the release process, in foresight of next release. Please edit it at will.

Pre-release:

- https://github.com/Unvanquished/Unvanquished/issues/3165

Tasklist

- [x] Emit notices to server owners about the upcoming release to give them time to prepare instances

## Release process:

- Prepare blog post
  * [x] Gather the changes (list commits)
  * [x] Summarize the changes (for the redactor)
  * [x] Write a blog post [WIP]
  * [x] Proof read blog post
- [x] Write release notes for server owners to ease the transition
- Merge
  * [x] Merge remaining PRs (see above)
  *  ~~Merge `for-0.55.1/sync` to master if exists~~
- [x] Commit version numbers and push commits
- Tag release
  * [x] tag release
  * [x] tag every submodule of Unvanquished and UnvanquishedAssets with `unvanquished/0.55.1`
  * [ ] tag Urcheon
  * [x] Push release tags
- Build release
  * Rebuild engine binaries
    - [x] Linux (linux-amd64, linux-i686, linux-arm64, linux-armhf)
    - [x] Windows (windows-amd64, windows-i686)
    - [x] macOS (macos-amd64)
  * Rebuild dpks
    - [x]  Rebuild game nexes
    - [x] Rebuild data
    - [x] Package dpks
    - [x] Package unizip
  * [x] Build and upload benchmark demo
  * [x] Check with validate-release
- Set up game servers
  * [x] unvanquished.net
  * [x] gg.illwieckz.net
- Set up distribution
  * [x] Upload unizip to dl.unvanquished.net
  * [x] Convert unizip to torrent in cdn.unvanquished.net
  * [x] Make sure CDN mirrors mirrored
  * [x] Upload to GitHub
  * [x] Run script to set 0.55.1 default download
  * [x] Run script to publish torrent
- [x] Publish blog post
- Social medias
  * [x] Write and publish Mastodon post
  * [x] Write and publish X post
  * [x] Write and publish Facebook post
  * [x] Write and publish Reddit post
- [x] `@everyone` and `@room` message as announcement post in Discord (bridged to Matrix)
- [x] Message on IRC
- [ ] Update flatpak recipe
- [x] Update version numbers on Wiki template: https://wiki.unvanquished.net/wiki/Template:Version

## Post-release things:

- [x] Make sure FOSS Torrents knows about the release
- [ ] Make sure Phoronix knows about the release
- [ ] Translate blog post for LinuxFr.org or make sure someone writes an article about the release (do 0.55 one)
- [x] Make sure sf.net mirrored the unizip.
- [x] Upload the unizip to IndieDB as a backup
- [ ] Copy blog post to IndieDB (do 0.55 one)
- [x] Duplicate this issue for 0.56.0

**Comment by illwieckz** [comment]
We need to update flatpak.

**Comment by illwieckz** [comment]
My commands for building the `0.55.1` release:

```sh
export GIT_AUTHOR_DATE='2024-11-03 05:55:00 +0000'; export GIT_COMMITTER_DATE="${GIT_AUTHOR_DATE}"
oldver='0.55.0'
ver='0.55.1'
oldbasename="unvanquished_${oldver}"
basename="unvanquished_${ver}"
unizip="${basename}.zip"
sumfile="${basename}.sha512sum"
demoname="unvanquished-benchmark_${ver}"
demofile="${demoname}.dm_86"
demoarchive="${demofile}.xz"

cd ~/dev/Unvanquished
git checkout master
git pull
git submodule update --init --recursive

./update-version-number.py "${ver}" minor

git -C daemon commit -am "bump version number to ${ver}"
# TODO: commit submodule
git commit -am "bump version number to ${ver}"

git -C daemon push
git push

git -C daemon tag -am "'Daemon ${ver} beta" "v${ver}"
git tag -am "'Unvanquished ${ver} beta" "v${ver}"

git-checkout-modules --print 2>/dev/null \
| tail -n +2 | cut -f1 -d' ' \
| sed -e "s/$(basename "$(realpath .)")/./" \
| xargs -I{} -P1 git -C {} tag -am "Unvanquished ${ver}" "unvanquished/${ver}"

cd ~/Mapping/Unvanquished/UnvanquishedAssets
git checkout master
git pull
git submodule update --init --recursive

cd pkg/tex-exm_src.dpkdir
(v=1.3.2; git tag -am "$(basename "$(realpath .)" '_src.dpkdir') v${v}" "v${v}")
cd ../map-parpax_src.dpkdir
(v=2.7.5; git tag -am "$(basename "$(realpath .)" '_src.dpkdir') v${v}" "v${v}")
cd ../map-perseus_src.dpkdir
(v=1.0.5; git tag -am "$(basename "$(realpath .)" '_src.dpkdir') v${v}" "v${v}")
cd ../map-yocto_src.dpkdir
(v=1.0.5; git tag -am "$(basename "$(realpath .)" '_src.dpkdir') v${v}" "v${v}")
cd ../..

git tag -am "'Unvanquished ${ver} beta" "v${ver}"

git-checkout-modules --print 2>/dev/null \
| tail -n +2 | cut -f1 -d' ' \
| sed -e "s/$(basename "$(realpath .)")/./" \
| xargs -I{} -P1 git -C {} tag -am "Unvanquished ${ver}" "unvanquished/${ver}"

export URCHEON_BUILD_PREFIX="$(realpath build)"

urcheon clean --package

urcheon prepare pkg/tex-exm_src.dpkdir

urcheon build pkg/tex-exm_src.dpkdir pkg/map-parpax_src.dpkdir pkg/map-perseus_src.dpkdir pkg/map-yocto_src.dpkdir ~/dev/Unvanquished/pkg/unvanquished_src.dpkdir

urcheon package pkg/tex-exm_src.dpkdir pkg/map-parpax_src.dpkdir pkg/map-perseus_src.dpkdir pkg/map-yocto_src.dpkdir ~/dev/Unvanquished/pkg/unvanquished_src.dpkdir

touch --date="${GIT_AUTHOR_DATE}" build/pkg/*dpk

find build/pkg -type f -name '*.dpk' -print0 | drt-multitask -0 -I{} -P2 drt-zipbrute --no-directories --touch --chmod -4 {}

cd ~/dev/unvanquished-release-scripts

ssh unvanquished-build-machine 'cd ~/dev/unvanquished-release-scripts; ./docker-build --reference 6b8fdb8f6030ce6a8266200855e2d2729178f521 --target all --unizip'

rm -r build/release
mkdir -p build/release
cd build/release
rsync -av unvanquished-build-machine:dev/unvanquished-release-scripts/build/release/unvanquished_0.zip .
7z x unvanquished_0.zip
mv unvanquished_0 "${basename}"
cd "${basename}"
mv symbols_0.zip "symbols_${ver}.zip"
find . -exec touch --date="${GIT_AUTHOR_DATE}" {} \;

find . -type f \( -name '*.zip' -o -name '*.dpk' \) -print0 | drt-multitask -0 -I{} -P2 drt-zipbrute --no-directories --touch --chmod -4 {}

cd pkg
cp -av ~/Mapping/Unvanquished/UnvanquishedAssets/build/pkg/*.dpk .
zipmerge -k "${basename}.dpk" vm_0.dpk
touch --date="${GIT_AUTHOR_DATE}" "${basename}.dpk"
rm vm_0.dpk

(cd ~/Jeux/PC/"${oldbasename}"/pkg; ls -1 *.dpk | grep -E -v '^unvanquished|^tex-exm|^map-parpax|^map-perseus|^map-yocto') \
| xargs -I{} -P1 cp -av ~/Jeux/PC/"${oldbasename}"/pkg/{} .

( export LC_ALL; md5sum --binary -- *.dpk | sed -e 's/\.dpk$//' | sort -k2,2 -t' ' | sed 's/$/.dpk/' ) | tee md5sums
touch --date="${GIT_AUTHOR_DATE}" md5sums

cd ../..
7z a -tzip -mx=0 "${unizip}" "${basename}"
touch --date="${GIT_AUTHOR_DATE}" "${unizip}"
drt-zipbrute --no-directories --chmod -4 "${unizip}"

~/dev/unvanquished-validate-release/validate_release.py "${unizip}"

sha512sum -b "${unizip}" > "${sumfile}"
touch -r "${unizip}" "${sumfile}"

rsync -av --progress "${unizip}" "${sumfile}" unvanquished.net:

cd ..
mkdir -p test
cd test
7z x "../release/${unizip}"
cd "${basename}"
7z x linux-amd64.zip

cd ~/dev/Unvanquished
cd tools/record-benchmark-demo
./record-benchmark-demo ~/dev/unvanquished-release-scripts/build/test/"${basename}"/daemon-tty
touch --date="${GIT_AUTHOR_DATE}" unvanquished-benchmark.dm_86
mv unvanquished-benchmark.dm_86 "${demofile}"

cp -av "${demofile}" ~/.local/share/unvanquished/demos
~/dev/unvanquished-release-scripts/build/test/"${basename}"/daemon -set common.shutdownOnDrop on +demo_play "${demoname}"

xz -9 -k "${demofile}"
rsync -av --progress "${demoarchive}" unvanquished.net:

cd ~/dev/Unvanquished
git-checkout-modules --print 2>/dev/null \
| tail -n +2 | cut -f1 -d' ' \
| sed -e "s/$(basename "$(realpath .)")/./"\
| xargs -I{} -P1 git -C {} push --tags

cd ~/Mapping/Unvanquished/UnvanquishedAssets
git-checkout-modules --print 2>/dev/null \
| tail -n +2 | cut -f1 -d' ' \
| sed -e "s/$(basename "$(realpath .)")/./"\
| xargs -I{} -P1 git -C {} push --tags

---

ssh unvanquished.net
sudo -s

oldver='0.55.0'
ver='0.55.1'
basename="unvanquished_${ver}"
unizip="${basename}.zip"
sumfile="${basename}.sha512sum"
demoname="unvanquished-benchmark_${ver}"
demofile="${demoname}.dm_86"
demoarchive="${demofile}.xz"

cd /var/www/dl.unvanquished.net/release
cp -av ~illwieckz/"${unizip}" ~illwieckz/"${sumfile}" .
chown www-data:www-data "${unizip}" "${sumfile}"

cd /var/www/dl.unvanquished.net/benchmark/demos
cp -av ~illwieckz/"${demoarchive}" .
chown www-data:www-data "${demoarchive}"

cd /var/www/tools/release
sed -e "s/${oldver}/${ver}/" -i configuration/current.conf
./cache-tracker-list
./unpack
./publish

# Write a GitHub release: https://github.com/Unvanquished/Unvanquished/releases/new
# Publish the GitHub release
# Write a blog post: https://unvanquished.net/wp-admin
# Publish the blog post

./announce
/etc/init.d/nginx configtest && systemctl reload nginx

su - unvserver

ver='0.55.1'
basename="unvanquished_${ver}"
unizip="${basename}.zip"

unvserver@daemon:~$ ./daemon-server stop default
Unvanquished 0.55 Linux amd64 Oct 19 2024
cmdline: -libpath /home/unvserver/version/default -homepath /home/unvserver/home/default +quit
[FS] Lib path: /home/unvserver/version/unvanquished_0.55.0
[FS] Home path: /home/unvserver/home/default
[FS] Pak search path: /home/unvserver/version/unvanquished_0.55.0/pkg
[FS] Pak search path: /home/unvserver/home/default/pkg
Warn: Could not acquire singleton lock: Resource temporarily unavailable
If you are sure no other instance is running, delete /home/unvserver/home/default/lock-server

cd version/
7z x "/var/www/dl.unvanquished.net/release/${unizip}"
ln -sfn "${basename}" default
```
