### ISSUE TITLE
Migrating NaCl toolchain From PNaCl to Saigo

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#3197]
Saigo allows us to get rid of PNaCl limitations (like old C++14 from Clang 3.6) before doing a bigger jump to Wasm:

- https://github.com/DaemonEngine/Daemon/issues/795

Roadmap:

- [ ] Add support for Saigo into the CMake build configuration:
  * [ ] https://github.com/DaemonEngine/Daemon/pull/981
  * [ ] https://github.com/Unvanquished/Unvanquished/pull/2862
- [ ] Make possible to build Lua and Freetype with Saigo:
  * [ ] https://github.com/Unvanquished/Unvanquished/pull/3195
  * [ ] https://github.com/DaemonEngine/Daemon/pull/1446
- [ ] Provide c/sgame dependencies as submodules:
  * [ ] Clone Lua repository
  * [ ] Patch Lua for NaCl
  * [ ] Add Lua as submodule
  * [ ] Clone Freetype repository
  * [ ] Add Freetype as submodule
- [ ] Provide Saigo in external_deps
   * [ ] Find a way to package Saigo compiler
   * [ ] Find a way to package Saigo binutils
   * [ ] Find a way to package libc/libc++
   * [ ] Package all of that in external_deps
- [ ] Fix bugs uncovered by Saigo:
   * [ ] https://github.com/DaemonEngine/Daemon/issues/1312
   * [ ] https://github.com/Unvanquished/Unvanquished/pull/3196

**Comment by illwieckz** [comment]
Non-blocking issues:

- [x] https://github.com/DaemonEngine/Daemon/issues/1504
  Same with PNaCl-built nexe, maybe a Linux kernel issue.
- [ ] https://github.com/Unvanquished/Unvanquished/issues/3286
  Same with PNaCl-built nexe, that's an NaCl loader issue.
  https://github.com/DaemonEngine/native_client/pull/8
- [ ] The Linux i686 debugger provided with PNaCl doesn't work with amd64 nexe
  Same with PNaCl-built nexe.

They are listed in a separate comment so they don't affect the completeness of the issue.

---

So, it's now possible with current `master` to build the game with Saigo. The Saigo toolchain isn't shipped yet with the external deps so one has to do fetch and install Saigo by hand.

It currently only works on Linux because Saigo isn't built for other platforms yet.

Here follow some instructions on how to get Saigo and build with it.

**Abstract:**

Download and extract https://dl.unvanquished.net/deps/linux-amd64-default_11.tar.xz and put the `saigo_newlib` folder in `daemon/external_deps/linux-amd64-default_10` to install the Saigo toolchain, then use the `-DBUILD_GAME_NACL=ON` CMake option to switch from the PNaCl toolchain to the Saigo toolchain before building.

**Full instructions:**

```sh
# Get the source
git clone https://github.com/Unvanquished/Unvanquished.git
cd Unvanquished

# Fetch all the submodules
git submodule update --init --recursive

# Install external deps with Saigo
cd daemon/external_deps
rm -rf linux-amd64-default_11
wget https://dl.unvanquished.net/deps/linux-amd64-default_10.tar.xz
tar xvf linux-amd64-default_11.tar.xz
cd linux-amd64-default_11
wget https://dl.illwieckz.net/b/saigo/preview/saigo_newlib_20241119.txz
tar xvf saigo_newlib_20241119.txz
cd ../../..

# Build with Saigo
mkdir -p build; cd build
cmake .. -DBUILD_GAME_NACL=ON -DUSE_NACL_SAIGO=ON
cmake --build . --parallel "$(nproc)"
```

**Comment by illwieckz** [comment]
So, here is the repository where I implement the compilation build script of Saigo:

- https://github.com/DaemonEngine/DaemonSaigoNativeClientToolkit

The toolchain binaries have been successfully rebuilt for:

||Linux|Windows|macOS|FreeBSD
-|-|-|-|-
amd64|✅️|✅️|✅️|✅️
i686|✅️|✅️|
arm64|✅️||✅️
armhf|✅️

Some informations on the binaries (here the C++ compiler and the linker for the amd64 nexe, per platform):

```
freebsd-amd64/prefix/bin/x86_64-nacl-clang++:     ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 13.3, FreeBSD-style, stripped
freebsd-amd64/prefix/bin/x86_64-nacl-ld.bfd:      ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 13.3, FreeBSD-style, stripped
linux-amd64/prefix/bin/x86_64-nacl-clang++:       ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=bcd4f4aff30f10c64e6515d41476459666385f2e, stripped
linux-amd64/prefix/bin/x86_64-nacl-ld.bfd:        ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=4d709354e7fef75946bfce8b24fa1727a352cd5f, stripped
linux-arm64/prefix/bin/x86_64-nacl-clang++:       ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=4d47428bd568c0bf8405b7be52e9141d646215a4, for GNU/Linux 3.7.0, stripped
linux-arm64/prefix/bin/x86_64-nacl-ld.bfd:        ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=543c7314b72e186f6da728f20d307f92bf11dcc4, for GNU/Linux 3.7.0, stripped
linux-armhf/prefix/bin/x86_64-nacl-clang++:       ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=6ca2e2971d760c15025c0bf0ac33ca4be4960f49, for GNU/Linux 3.2.0, stripped
linux-armhf/prefix/bin/x86_64-nacl-ld.bfd:        ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=52ad3c6b880745c5f16058c2734d4bae4b15dd79, for GNU/Linux 3.2.0, stripped
linux-i686/prefix/bin/x86_64-nacl-clang++:        ELF 32-bit LSB pie executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=98e2f239f5d7123a788eaf759e66e873d5bd3e67, for GNU/Linux 3.2.0, stripped
linux-i686/prefix/bin/x86_64-nacl-ld.bfd:         ELF 32-bit LSB pie executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=0936276e32670e43facdafbeed7a1c3d6d56d7fe, for GNU/Linux 3.2.0, stripped
macos-amd64/prefix/bin/x86_64-nacl-clang++:       Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
macos-amd64/prefix/bin/x86_64-nacl-ld.bfd:        Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
macos-arm64/prefix/bin/x86_64-nacl-clang++:       Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
macos-arm64/prefix/bin/x86_64-nacl-ld.bfd:        Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
windows-amd64/prefix/bin/x86_64-nacl-clang++.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows, 11 sections
windows-amd64/prefix/bin/x86_64-nacl-ld.bfd.exe:  PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows, 10 sections
windows-i686/prefix/bin/x86_64-nacl-clang++.exe:  PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows, 9 sections
windows-i686/prefix/bin/x86_64-nacl-ld.bfd.exe:   PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows, 9 sections
```

The NaCl libc and libc++ aren't fetched yet so the built toolchains are still unusable.

Once this is done, it means the Saigo toolchain will be usable on any platform that can run the game.

With PNaCl only some Windows and Linux platforms can run the toolchain (no toolchain for Arm), it is broken with macOS and FreeBSD can't run the pexe translator on Linuxulator. So this will be a big progress, as any platform that can run the engine (and run the nacl game, either natively or through some compatibility layer) would be able to be a working development platform running the toolchain natively.

**Comment by slipher** [comment]
Debugging update:
- [Interactive debugging](https://wiki.unvanquished.net/wiki/Native_Client#Interactive_Debugging) remains somewhat usable. Tested with an old nacl-gdb.
- Postmortem crash analysis (which we actually use) does not work. Breakpad's dump_syms [crashes](https://github.com/DaemonEngine/Daemon/pull/1501#issuecomment-2597209415) when fed an nexe build by Saigo. Using the upstream Breakpad makes no difference.

**Comment by illwieckz** [comment]
Here is the most recent Google build of Saigo for Linux amd64, repackaged:

- https://dl.illwieckz.net/b/saigo/preview/saigo_newlib_20250219.txz

To use it, the `saigo_newlib` folder should be stored in the deps folder, so basically `external_deps/linux-amd64-default_10/saigo_newlib`.

It is based on Clang 20:

```
$ saigo_newlib/bin/x86_64-nacl-clang -v 2>&1 | head -n3
clang version 20.0.0git (https://chromium.googlesource.com/a/native_client/nacl-llvm-project-v10.git 0b939f58669775bad14c93d6d89ce046600e8eb4)
Target: x86_64-unknown-nacl
Thread model: posix
```

**Comment by illwieckz** [comment]
Excellent!

**Comment by illwieckz** [comment]
> Then I tried to build irt_core with a Saigo toolchain produced from https://github.com/DaemonEngine/DaemonSaigoNativeClientToolkit, but hit a snag that most headers are missing.

Yes the whole nexe libc/libc++ isn't installed yet by this repository. I'll start with copying them from google builds (rebuilding them is much more complicated as it requires some very old nacl gcc).

**Comment by slipher** [comment]
Where is the build system for the libc/libc++?

**Comment by illwieckz** [comment]
No idea. I know it can be built from the `native_client` directory using some of those commands from there:

- https://web.archive.org/web/20250909063822/https://www.chromium.org/nativeclient/pnacl/building-pnacl-components-for-distribution-packagers/

I have some captured logs (or can capture them again), and it's a real mess to build. And it depends on an old GCC.

**Comment by illwieckz** [comment]
> I have some captured logs (or can capture them again), and it's a real mess to build. And it depends on an old GCC.

The prebuilt `native_client/toolchain/linux_x86/nacl_x86_glibc/bin/x86_64-nacl-gcc` says how it was built with the `-v` option:

```
$ depot/native_client/toolchain/linux_x86/nacl_x86_glibc/bin/x86_64-nacl-gcc -v
Using built-in specs.
Target: x86_64-nacl
Configured with: /mnt/data/b/build/slave/nacl-toolchain/build/native_client/tools/SRC/gcc/configure CC='gcc -m32' CFLAGS='-O2 -g -Dinhibit_libc -D__gthr_posix_h' LDFLAGS=-s 'CFLAGS_FOR_TARGET=-O2 -g ' 'CXXFLAGS_FOR_TARGET=-O2 -g ' --prefix=/mnt/data/b/build/slave/nacl-toolchain/build/native_client/tools/toolchain/linux_x86 --disable-decimal-float --disable-libgomp --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --target=x86_64-nacl --enable-linker-build-id --with-gmp=/mnt/data/b/build/slave/nacl-toolchain/build/native_client/tools/BUILD/.gcc-extra-install-gmp --with-mpfr=/mnt/data/b/build/slave/nacl-toolchain/build/native_client/tools/BUILD/.gcc-extra-install-mpfr --with-ppl=/mnt/data/b/build/slave/nacl-toolchain/build/native_client/tools/BUILD/.gcc-extra-install-ppl --with-host-libstdcxx='-lpwl -Wl,-Bstatic -lstdc++ -Wl,-Bdynamic -lm' --with-cloog=/mnt/data/b/build/slave/nacl-toolchain/build/native_client/tools/BUILD/.gcc-extra-install-cloog-ppl --disable-ppl-version-check --enable-shared --enable-languages=c,c++,objc,obj-c++,fortran --enable-threads=posix --enable-tls
Thread model: posix
gcc version 4.4.3 20150713 (Native Client 9ff1dc0c05b45941b86bed303a87a9eac17192ea, Git Commit f80d6b9ee7f94755c697ffb7194fb01dd0c537dd) (GCC) 
```

The repository is cloned in `native_client/tools/SRC/gcc`, the upstream is `https://chromium.googlesource.com/native_client/nacl-gcc.git` which has `f80d6b9ee7f94755c697ffb7194fb01dd0c537dd` as more recent commit in `main` from 10 years ago.

It is believed this nacl-gcc is required to buikd some libc components.

**Comment by illwieckz** [comment]
That `nacl-gcc` is very old and relies on a very old `ppl` that doesn't build without using a very old GCC, meaning we need to compile and old compiler to compile and old compiler to compile some parts of the libc. That's too much work for now.

The good thing is that:

- Google kept updating their nacl libc/libc++ build, for example the latest nacl libc++ is from Clang 21.
- The nacl libc/libc++ is meant to run in the untrusted context, so even when we copy paste those libs from Google, as long as the user rebuilds the saigo compiler and binutils, the user is guaranteed to not run prebuilt binaries in trusted context. Those libs never run outside of the virtual machine.

I have a proof of concept that rebuilds the saigo compiler and binutils and package google's nacl libc/libc++, I managed to build with it an `helloworld.nexe` and to run it with a rebuilt nacl_loader. That's very good.

**Comment by illwieckz** [comment]
So, here is the status:

- Saigo is now rebuildable since months,
- I recently managed to automatize the fetching of precompiled Saigo libc/libc++.

That means we are now able to repackage a working Saigo toolchain for any platform we support (and more), which brings a toolchain to platform we could not build nexe on (that's more platforms that PNaCl supported), and brings Clang 21 for the game code and then very recent C++ standards.

- We do know how to rebuild the loader,
- We do know how to build a 16k page size loader.

That means we are now able to repackage a more recent loader for any platform we support, and we can now support 16k Arm kernels, which original NaCl didn't (that's more systems than before!).

That brings a lot of good things.

Compiler availability:

||Before|After|
|-|-|-|
|Windows amd64|✅️|✅️
|Windows i686|✅️|✅️
|Linux amd64|✅️|✅️
|Linux i686|❌️|✅️
|Linux arm64|❌️|✅️
|Linux armhf|❌️|✅️
|macOS amd64|✅️¹|✅️
|macOS arm64|❌️|✅️
|FreeBSD amd64|❌️|✅️
|Anything else|❌️|✅️ very likely, untested

Language support:

||Before|After|
|-|-|-|
|Clang|3.6|21
|C|11|18
|C++|12, partial 14|23

The highest engine C++ version is currently C++17 because we build the Linux engines on Debian Buster with GCC 12, we build the NaCl nexe in a separate environment and Saigo would run anywhere we build it anyway, so we can either raise the required C++ version from 14 to 17 or even 23 for the game code. C++17 would be a good start. We need to support an higher C++ version to build more recent RmlUi versions that supports Harfbuzz for complete language rendering.

System support:

||Before|After|
|-|-|-|
|Windows amd64|✅️|✅️
|Windows i686|✅️|✅️
|Linux arm64 with 16k page size and 32-bit compatibility|❌️|✅️
|Linux arm64 with 4k page size and 32-bit compatibility|✅️|✅️
|Linux arm64 without 32-bit compatibility²|❌️|❌️
|Linux armhf with 16k page size|❌️|✅️
|Linux armhf with 4k page size|✅️|✅️
|macOS amd64|✅️|✅️
|macOS arm64 with Rosetta 2|✅️|✅️
|FreeBSD amd64 with Linuxulator|✅️|✅️
|Anything else|❌️|❌️

The Clang 21 bump and the 16k kernel page size compatibility buy us a lot of time (years?) before being required to migrate to Wasm. This makes us able to focus on other things in the short and medium term like upgrading RmlUi with Harfbuzz support, and other things which is really wanted to improve internationalization and then accessibility.

Once the migration to Saigo and the new loader is done, it will buy us time to focus on some user things, while letting the Wasm ecosystem more time to mature.

____
¹ I'm not sure the PNaCl compiler was working correctly on macOS.
² I have heard that some systems like Asahi Linux disables 32-bit compatibility in kernel, which is surprising given how much effort on foreign compatibility has been poured into it, with both amd64 and 4k page size compatibility brought through FEX and other things. It would be a shame if that's true.

**Comment by illwieckz** [comment]
I renamed `DaemonSaigoNativeClientToolkit` as `saigo-release-scripts`.

At the time I created this `DaemonSaigoNativeClientToolkit` repository I was thinking about it for building the whole Native Client stuff: compilers and loaders.

But the loader has its own repository and build scripts are written there:

- https://github.com/DaemonEngine/native_client

So in the end the `DaemonSaigoNativeClientToolkit` repository was only meant to rebuild the Saigo toolchain.

So I renamed it `saigo-release-scripts`:

- https://github.com/DaemonEngine/saigo-release-scripts

**Comment by illwieckz** [comment]
I can rebuild a working NaCl game with a Saigo built using [saigo-release-scripts](https://github.com/DaemonEngine/saigo-release-scripts).

**Comment by illwieckz** [comment]
In `saigo-release-scripts` you run:

```sh
tools/release/build linux-amd64
```

Then you copy, move or symlink `saigo-release/scripts/build/linux-amd64/prefix` as `Unvanquished/daemon/external_deps/linux-amd64-default_11/saigo_newlib`.

And then you build Unvanquished with `cmake -DBUILD_GAME_NACL_TARGETS=ON -DUSE_NACL_SAIGO=ON`.

Beware that building Clang is a really heavy computation, and some linking tasks may eat up 8GB each.

**Comment by slipher** [comment]
> ¹ I'm not sure the PNaCl compiler was working correctly on macOS.

I'm not aware of any issues. That may have been some confusion where the only person testing it there was also using Ninja + PCH or something.

> ² I have heard that some systems like Asahi Linux disables 32-bit compatibility in kernel,

It would make sense, since 32-bit compatibility is disabled in the hardware.



> Beware that building Clang is a really heavy computation, and some linking tasks may eat up 8GB each.

Having USE_LTO on is a very bad default. I recall trying your build script a year or two ago, and it killed almost every app on my machine thanks to that default.

**Comment by illwieckz** [comment]
> Having USE_LTO on is a very bad default. I recall trying your build script a year or two ago, and it killed almost every app on my machine thanks to that default.

Right, it looks like I forgot to disable it. The release script was especially written to not set it by default but then the CMake default remained, oops! 😅️

**Comment by illwieckz** [comment]
Anyway this is fixed, and when using the `tools/release/build` tool, it selects as job count `min(nproc, freemem/8)`.

**Comment by illwieckz** [comment]
I just published the first release of our Saigo Compiler Collection:

- https://github.com/DaemonEngine/saigo-release-scripts/releases/tag/v21.0-20260625

The Linux amd64 build has been verified to be able to build working Unvanquished cgame and sgame for amd64.

Once extracted, the directories like `saigocc-linux-amd64_21.0-20260625` can just be renamed to `saigo_newlib` and placed in directories like `external_deps/linux-amd64-default_11`, and this will be used for building Unvanquished when using the `-DUSE_NACL_SAIGO=ON` cmake option.

**Comment by slipher** [comment]
> * The Linux i686 debugger provided with PNaCl doesn't work with amd64 nexe
>       Same with PNaCl-built nexe.

That has no relation to migrating to Saigo, but it's possible to get it to run (assuming you have the 32-bit environment and compilers installed) like this:
```
wget https://ftp.gnu.org/gnu/ncurses/ncurses-6.6.tar.gz  # the newest version
tar -xzf ncurses-6.6.tar.gz 
cd ncurses-6.6/
# TODO: add appropriately arch-specific install prefix; disable man pages
./configure --with-abi-version=5 --with-shared --host=i686-linux-gnu
make
sudo make install
```

**Comment by illwieckz** [comment]
I published a new release of the Saigo SDK:

- https://github.com/DaemonEngine/saigo-nacl-sdk/releases/tag/v21.0-20260625

The windows build should not require MinGW libraries anymore.

I also renamed the repository to `saigo-nacl-sdk`.

I was thinking about naming it `saigocc` (like icc or [aocc](https://www.amd.com/en/developer/aocc.html)), but naming it `saigo-sdk` is consistant with industry usages like `wasi-sdk` which is very similar in purpose (a repository to rebuild a vm toolchain, not containing the source, just repository references and patches) but for different technologies:

- https://github.com/WebAssembly/wasi-sdk

I thought making it obvious from the name it is about nacl was good (unlike wasi, the saigo name doesn't contain anything related to nacl), so I went for `saigo-nacl-sdk`.

It's possible that future release packages will be named `saigosdk-<target>_version.tar.xz` instead of `saigocc-<target>_version.tar.xz` as I did first, to be consistent with the repository name.

**Comment by illwieckz** [comment]
See, this also include a detailed description of the current status:

- https://github.com/Unvanquished/Unvanquished/issues/3570

**Comment by illwieckz** [comment]
Breakpad fix for Saigo-built nexe:

- https://github.com/DaemonEngine/breakpad/pull/19

We now have no know regression when moving to Saigo! 🎉️
