### ISSUE TITLE
Port CGame to NaCl

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#418]
And completely nuke QVMs. This is a tracking bug as cgame NaCl will be a long project.

This issue depends on
- [x] #448 CG_GetBindings makes a lot of syscalls
- [x] #471 On NaCl CGame the sprint bar doesn't show
- [x] #472 Loads of "command foo already registered" when loading a map in NaCl CGame
- [x] #474 Kharnov's testing: decal and trail problems
- [x] #550 Make shared mem command buffers awesome
- [x] #551 Move librocket to CGame

**Comment by DolceTriade** [comment]
Fixed?
